/*
Copyright (C) 2017-2019 OpenIO SAS, as part of OpenIO SDS

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "rdir_variables.h" /* AUTO-GENERATED by confgen.py */

guint rdir_fd_per_base = OIO_RDIR_FD_PER_BASE;
guint rdir_fd_reserve = OIO_RDIR_FD_RESERVE;

static void __attribute__ ((constructor))
_declare_gboolean_OIO__OIO_SDS_RDIR_RDIR_VARIABLES_H_ (void) {

	oio_var_register_guint(
		&rdir_fd_per_base, OIO_VARKIND_size, "rdir.fd_per_base",
		"Configure the maximum number of file descriptors allowed to each leveldb database. Set to 0 to autodetermine the value (cf. rdir.fd_reserve). The real value will be clamped at least to 8. Will only be applied on bases opened after the configuration change.",
		OIO_RDIR_FD_PER_BASE, 0, 16384);

	oio_var_register_guint(
		&rdir_fd_reserve, OIO_VARKIND_size, "rdir.fd_reserve",
		"Configure the total number of file descriptors the leveldb backend may use. Set to 0 to autodetermine the value. Will only be applied on bases opened after the configuration change.",
		OIO_RDIR_FD_RESERVE, 0, 32768);
}
