/*
Copyright (C) 2017-2019 OpenIO SAS, as part of OpenIO SDS

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef OIO__OIO_SDS_RDIR_RDIR_VARIABLES_H_
#define OIO__OIO_SDS_RDIR_RDIR_VARIABLES_H_

#include "core/oiovar.h"

/* AUTO-GENERATED by confgen.py */

#ifndef OIO_RDIR_FD_PER_BASE
# define OIO_RDIR_FD_PER_BASE (0)
#endif

extern guint rdir_fd_per_base;

#ifndef OIO_RDIR_FD_RESERVE
# define OIO_RDIR_FD_RESERVE (0)
#endif

extern guint rdir_fd_reserve;


#endif /* OIO__OIO_SDS_RDIR_RDIR_VARIABLES_H_ */
