/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "AWL-MetaDirectory-Protocol"
 * 	found in "//oio-sds/metautils/lib/description.asn"
 * 	`asn1c -fwide-types -fcompound-names -fskeletons-copy`
 */

#ifndef	_M2V2BeanSequence_H_
#define	_M2V2BeanSequence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct M2V2Bean;

/* M2V2BeanSequence */
typedef struct M2V2BeanSequence {
	A_SEQUENCE_OF(struct M2V2Bean) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} M2V2BeanSequence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_M2V2BeanSequence;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "M2V2Bean.h"

#endif	/* _M2V2BeanSequence_H_ */
#include <asn_internal.h>
