/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "AWL-MetaDirectory-Protocol"
 * 	found in "//oio-sds/metautils/lib/description.asn"
 * 	`asn1c -fwide-types -fcompound-names -fskeletons-copy`
 */

#include "M2V2Bean.h"

static asn_TYPE_member_t asn_MBR_M2V2Bean_1[] = {
	{ ATF_POINTER, 4, offsetof(struct M2V2Bean, alias),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_M2V2Alias,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alias"
		},
	{ ATF_POINTER, 3, offsetof(struct M2V2Bean, header),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_M2V2ContentHeader,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"header"
		},
	{ ATF_POINTER, 2, offsetof(struct M2V2Bean, chunk),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_M2V2Chunk,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"chunk"
		},
	{ ATF_POINTER, 1, offsetof(struct M2V2Bean, prop),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_M2V2Property,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"prop"
		},
};
static const ber_tlv_tag_t asn_DEF_M2V2Bean_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_M2V2Bean_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* alias */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* header */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* chunk */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* prop */
};
static asn_SEQUENCE_specifics_t asn_SPC_M2V2Bean_specs_1 = {
	sizeof(struct M2V2Bean),
	offsetof(struct M2V2Bean, _asn_ctx),
	asn_MAP_M2V2Bean_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_M2V2Bean = {
	"M2V2Bean",
	"M2V2Bean",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_M2V2Bean_tags_1,
	sizeof(asn_DEF_M2V2Bean_tags_1)
		/sizeof(asn_DEF_M2V2Bean_tags_1[0]), /* 1 */
	asn_DEF_M2V2Bean_tags_1,	/* Same as above */
	sizeof(asn_DEF_M2V2Bean_tags_1)
		/sizeof(asn_DEF_M2V2Bean_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_M2V2Bean_1,
	4,	/* Elements count */
	&asn_SPC_M2V2Bean_specs_1	/* Additional specs */
};

