/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "AWL-MetaDirectory-Protocol"
 * 	found in "//oio-sds/metautils/lib/description.asn"
 * 	`asn1c -fwide-types -fcompound-names -fskeletons-copy`
 */

#include "M2V2BeanSequence.h"

static asn_TYPE_member_t asn_MBR_M2V2BeanSequence_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_M2V2Bean,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_M2V2BeanSequence_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_M2V2BeanSequence_specs_1 = {
	sizeof(struct M2V2BeanSequence),
	offsetof(struct M2V2BeanSequence, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_M2V2BeanSequence = {
	"M2V2BeanSequence",
	"M2V2BeanSequence",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_M2V2BeanSequence_tags_1,
	sizeof(asn_DEF_M2V2BeanSequence_tags_1)
		/sizeof(asn_DEF_M2V2BeanSequence_tags_1[0]), /* 1 */
	asn_DEF_M2V2BeanSequence_tags_1,	/* Same as above */
	sizeof(asn_DEF_M2V2BeanSequence_tags_1)
		/sizeof(asn_DEF_M2V2BeanSequence_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_M2V2BeanSequence_1,
	1,	/* Single element */
	&asn_SPC_M2V2BeanSequence_specs_1	/* Additional specs */
};

