/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "AWL-MetaDirectory-Protocol"
 * 	found in "//oio-sds/metautils/lib/description.asn"
 * 	`asn1c -fwide-types -fcompound-names -fskeletons-copy`
 */

#ifndef	_Meta0Info_H_
#define	_Meta0Info_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include "AddrInfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Meta0Info */
typedef struct Meta0Info {
	OCTET_STRING_t	 prefix;
	AddrInfo_t	 addr;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Meta0Info_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Meta0Info;

#ifdef __cplusplus
}
#endif

#endif	/* _Meta0Info_H_ */
#include <asn_internal.h>
