/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "AWL-MetaDirectory-Protocol"
 * 	found in "//oio-sds/metautils/lib/description.asn"
 * 	`asn1c -fwide-types -fcompound-names -fskeletons-copy`
 */

#ifndef	_NamespaceInfo_H_
#define	_NamespaceInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>
#include <INTEGER.h>
#include "ParameterSequence.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ParameterSequence;

/* NamespaceInfo */
typedef struct NamespaceInfo {
	PrintableString_t	 name;
	INTEGER_t	*chunkSize	/* OPTIONAL */;
	struct ParameterSequence	*options	/* OPTIONAL */;
	ParameterSequence_t	 storagePolicy;
	ParameterSequence_t	 dataSecurity;
	ParameterSequence_t	 servicePools;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NamespaceInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NamespaceInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ParameterSequence.h"

#endif	/* _NamespaceInfo_H_ */
#include <asn_internal.h>
