/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "AWL-MetaDirectory-Protocol"
 * 	found in "//oio-sds/metautils/lib/description.asn"
 * 	`asn1c -fwide-types -fcompound-names -fskeletons-copy`
 */

#ifndef	_Parameter_H_
#define	_Parameter_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Parameter */
typedef struct Parameter {
	PrintableString_t	 name;
	OCTET_STRING_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Parameter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Parameter;

#ifdef __cplusplus
}
#endif

#endif	/* _Parameter_H_ */
#include <asn_internal.h>
