/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "AWL-MetaDirectory-Protocol"
 * 	found in "//oio-sds/metautils/lib/description.asn"
 * 	`asn1c -fwide-types -fcompound-names -fskeletons-copy`
 */

#ifndef	_RowFieldSequence_H_
#define	_RowFieldSequence_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RowField;

/* RowFieldSequence */
typedef struct RowFieldSequence {
	A_SEQUENCE_OF(struct RowField) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RowFieldSequence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RowFieldSequence;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RowField.h"

#endif	/* _RowFieldSequence_H_ */
#include <asn_internal.h>
