/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "AWL-MetaDirectory-Protocol"
 * 	found in "//oio-sds/metautils/lib/description.asn"
 * 	`asn1c -fwide-types -fcompound-names -fskeletons-copy`
 */

#ifndef	_RowField_H_
#define	_RowField_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include "RowFieldValue.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RowField */
typedef struct RowField {
	INTEGER_t	 pos;
	RowFieldValue_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RowField_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RowField;

#ifdef __cplusplus
}
#endif

#endif	/* _RowField_H_ */
#include <asn_internal.h>
