/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "AWL-MetaDirectory-Protocol"
 * 	found in "//oio-sds/metautils/lib/description.asn"
 * 	`asn1c -fwide-types -fcompound-names -fskeletons-copy`
 */

#ifndef	_RowFieldValue_H_
#define	_RowFieldValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <REAL.h>
#include <OCTET_STRING.h>
#include <PrintableString.h>
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RowFieldValue_PR {
	RowFieldValue_PR_NOTHING,	/* No components present */
	RowFieldValue_PR_i,
	RowFieldValue_PR_f,
	RowFieldValue_PR_b,
	RowFieldValue_PR_s,
	RowFieldValue_PR_n
} RowFieldValue_PR;

/* RowFieldValue */
typedef struct RowFieldValue {
	RowFieldValue_PR present;
	union RowFieldValue_u {
		INTEGER_t	 i;
		REAL_t	 f;
		OCTET_STRING_t	 b;
		PrintableString_t	 s;
		NULL_t	 n;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RowFieldValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RowFieldValue;

#ifdef __cplusplus
}
#endif

#endif	/* _RowFieldValue_H_ */
#include <asn_internal.h>
