/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "AWL-MetaDirectory-Protocol"
 * 	found in "//oio-sds/metautils/lib/description.asn"
 * 	`asn1c -fwide-types -fcompound-names -fskeletons-copy`
 */

#ifndef	_ServiceTag_H_
#define	_ServiceTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>
#include <BOOLEAN.h>
#include <INTEGER.h>
#include <REAL.h>
#include <OCTET_STRING.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ServiceTag__value_PR {
	ServiceTag__value_PR_NOTHING,	/* No components present */
	ServiceTag__value_PR_b,
	ServiceTag__value_PR_i,
	ServiceTag__value_PR_r,
	ServiceTag__value_PR_s
} ServiceTag__value_PR;

/* ServiceTag */
typedef struct ServiceTag {
	PrintableString_t	 name;
	struct ServiceTag__value {
		ServiceTag__value_PR present;
		union ServiceTag__value_u {
			BOOLEAN_t	 b;
			INTEGER_t	 i;
			REAL_t	 r;
			OCTET_STRING_t	 s;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServiceTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceTag;

#ifdef __cplusplus
}
#endif

#endif	/* _ServiceTag_H_ */
#include <asn_internal.h>
