/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "AWL-MetaDirectory-Protocol"
 * 	found in "//oio-sds/metautils/lib/description.asn"
 * 	`asn1c -fwide-types -fcompound-names -fskeletons-copy`
 */

#ifndef	_TableVersion_H_
#define	_TableVersion_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>
#include <INTEGER.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TableVersion */
typedef struct TableVersion {
	PrintableString_t	 name;
	INTEGER_t	 version;
	INTEGER_t	 when;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TableVersion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TableVersion;

#ifdef __cplusplus
}
#endif

#endif	/* _TableVersion_H_ */
#include <asn_internal.h>
