/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "AWL-MetaDirectory-Protocol"
 * 	found in "//oio-sds/metautils/lib/description.asn"
 * 	`asn1c -fwide-types -fcompound-names -fskeletons-copy`
 */

#ifndef	_Table_H_
#define	_Table_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include "TableHeader.h"
#include "RowSet.h"
#include <INTEGER.h>
#include <PrintableString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Table */
typedef struct Table {
	OCTET_STRING_t	 name;
	TableHeader_t	 header;
	RowSet_t	 rows;
	INTEGER_t	*status	/* OPTIONAL */;
	PrintableString_t	*statusString	/* OPTIONAL */;
	INTEGER_t	*localChanges	/* OPTIONAL */;
	INTEGER_t	*totalChanges	/* OPTIONAL */;
	INTEGER_t	*lastRowId	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Table_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Table;

#ifdef __cplusplus
}
#endif

#endif	/* _Table_H_ */
#include <asn_internal.h>
