/*
Copyright (C) 2017-2019 OpenIO SAS, as part of OpenIO SDS

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library.
*/

#include "client_variables.h" /* AUTO-GENERATED by confgen.py */

gint64 oio_chunk_size_maximum = OIO_CORE_CHUNK_SIZE_MAX;
gint64 oio_chunk_size_minimum = OIO_CORE_CHUNK_SIZE_MIN;
gchar oio_core_http_user_agent [64] = OIO_CORE_HTTP_USER_AGENT;
gint64 _refresh_cpu_idle = OIO_CORE_PERIOD_REFRESH_CPU_IDLE;
gint64 _refresh_io_idle = OIO_CORE_PERIOD_REFRESH_IO_IDLE;
gint64 _refresh_major_minor = OIO_CORE_PERIOD_REFRESH_MAJOR_MINOR;
gboolean oio_sds_client_patch_metachunk_size = OIO_CORE_SDS_ADAPT_METACHUNK_SIZE;
gboolean oio_sds_default_autocreate = OIO_CORE_SDS_AUTOCREATE;
gboolean oio_sds_no_shuffle = OIO_CORE_SDS_NOSHUFFLE;
gboolean oio_url_must_be_unicode = OIO_CORE_SDS_STRICT_UTF8;
gdouble oio_client_rawx_timeout_cnx = OIO_CORE_SDS_TIMEOUT_CNX_RAWX;
gdouble oio_client_rawx_timeout_req = OIO_CORE_SDS_TIMEOUT_REQ_RAWX;
gchar oio_sds_client_version [64] = OIO_CORE_SDS_VERSION;
gint64 meta2_max_versions = OIO_META2_MAX_VERSIONS;
guint oio_socket_proxy_buflen = OIO_SOCKET_PROXY_BUFLEN;
guint oio_socket_rawx_buflen = OIO_SOCKET_RAWX_BUFLEN;
gdouble oio_sqlx_timeout_req = OIO_SQLX_OUTGOING_TIMEOUT_REQ;

static void __attribute__ ((constructor))
_declare_gboolean_OIO__OIO_SDS_CORE_CLIENT_VARIABLES_H_ (void) {

	oio_var_register_gint64(
		&oio_chunk_size_maximum, OIO_VARKIND_size, "core.chunk_size.max",
		"Should the C API adjust the chunk size when over this ceiling. Set to 0 for no action.",
		OIO_CORE_CHUNK_SIZE_MAX, 0, G_MAXINT64);

	oio_var_register_alias("core.chunk_size.max", "core.chunk_size.maximum");
	oio_var_register_gint64(
		&oio_chunk_size_minimum, OIO_VARKIND_size, "core.chunk_size.min",
		"Should the C API adjust the chunk size when below this threshold. Set to 0 for no action",
		OIO_CORE_CHUNK_SIZE_MIN, 0, G_MAXINT64);

	oio_var_register_alias("core.chunk_size.min", "core.chunk_size.minimum");
	oio_var_register_string(
		oio_core_http_user_agent, "core.http.user_agent",
		"HTTP User-Agent to be used between any C client and the proxy",
		OIO_CORE_HTTP_USER_AGENT, 64);

	oio_var_register_gint64(
		&_refresh_cpu_idle, OIO_VARKIND_time, "core.period.refresh.cpu_idle",
		"Sets the miniimal amount of time between two refreshed of the known CPU-idle counters for the current host. Keep this value small.",
		OIO_CORE_PERIOD_REFRESH_CPU_IDLE, 100 * G_TIME_SPAN_MILLISECOND, 1 * G_TIME_SPAN_HOUR);

	oio_var_register_gint64(
		&_refresh_io_idle, OIO_VARKIND_time, "core.period.refresh.io_idle",
		"Sets the minimal amount of time between two refreshes of the known IO-idle counters for the current host. Keep this small.",
		OIO_CORE_PERIOD_REFRESH_IO_IDLE, 100 * G_TIME_SPAN_MILLISECOND, 1 * G_TIME_SPAN_HOUR);

	oio_var_register_gint64(
		&_refresh_major_minor, OIO_VARKIND_time, "core.period.refresh.major_minor",
		"Sets the minimal amount of time between two refreshes of the list of the major/minor numbers of the known devices, currently mounted on the current host. If the set of mounted file systems doesn't change, keep this value high.",
		OIO_CORE_PERIOD_REFRESH_MAJOR_MINOR, 100 * G_TIME_SPAN_MILLISECOND, 1 * G_TIME_SPAN_HOUR);

	oio_var_register_gboolean(
		&oio_sds_client_patch_metachunk_size, "core.sds.adapt_metachunk_size",
		"Should the client adapt metachunk size to EC policy parameters? Letting this on will make bigger metachunks, but chunks on storage will stay at normal chunk size. Disabling this option allows clients to do write alignment.",
		OIO_CORE_SDS_ADAPT_METACHUNK_SIZE);

	oio_var_register_gboolean(
		&oio_sds_default_autocreate, "core.sds.autocreate",
		"In the current oio-sds client SDK, should the entities be autocreated while accessed for the first time. So, when pushing a content in a container, when this option is set to 'true', the USER and the CONTAINER will be created and configured to the namespace's defaults.",
		OIO_CORE_SDS_AUTOCREATE);

	oio_var_register_gboolean(
		&oio_sds_no_shuffle, "core.sds.noshuffle",
		"In the current oio-sds client SDK, should the rawx services be shuffled before accessed. This helps ensuring a little load-balancing on the client side.",
		OIO_CORE_SDS_NOSHUFFLE);

	oio_var_register_gboolean(
		&oio_url_must_be_unicode, "core.sds.strict_utf8",
		"Should the object URLs be checked for non-UTF-8 characters? Disable this only if you have trouble reading old objects, uploaded before we check for invalid names.",
		OIO_CORE_SDS_STRICT_UTF8);

	oio_var_register_gdouble(
		&oio_client_rawx_timeout_cnx, OIO_VARKIND_time, "core.sds.timeout.cnx.rawx",
		"Sets the connection timeout for requests issued to rawx services.",
		OIO_CORE_SDS_TIMEOUT_CNX_RAWX, 0.001, 300.0);

	oio_var_register_gdouble(
		&oio_client_rawx_timeout_req, OIO_VARKIND_time, "core.sds.timeout.req.rawx",
		"Sets the global timeout when uploading a chunk to a rawx service.",
		OIO_CORE_SDS_TIMEOUT_REQ_RAWX, 0.001, 600.0);

	oio_var_register_string(
		oio_sds_client_version, "core.sds.version",
		"The version of the sds. It's used to know the expected metadata of a chunk",
		OIO_CORE_SDS_VERSION, 64);

	oio_var_register_gint64(
		&meta2_max_versions, OIO_VARKIND_size, "meta2.max_versions",
		"Namespace configuration of the max number of versions for a single alias, in a container.",
		OIO_META2_MAX_VERSIONS, -1, G_MAXINT64);

	oio_var_register_guint(
		&oio_socket_proxy_buflen, OIO_VARKIND_size, "socket.proxy.buflen",
		"Advice the libcurl to use that buffer size for the interactions with the proxy. libcurl gives no guaranty to take the advice into account. Set to 0 to let the default. libcurl applies its own range, usually between 1k and 512k.",
		OIO_SOCKET_PROXY_BUFLEN, 0, 512000);

	oio_var_register_guint(
		&oio_socket_rawx_buflen, OIO_VARKIND_size, "socket.rawx.buflen",
		"Advice the libcurl to use that buffer size for the interactions with the rawx services. libcurl gives no guaranty to take the advice into account. Set to 0 to let the default. libcurl applies its own range, usually between 1k and 512k.",
		OIO_SOCKET_RAWX_BUFLEN, 0, 512000);

	oio_var_register_gdouble(
		&oio_sqlx_timeout_req, OIO_VARKIND_time, "sqlx.outgoing.timeout.req",
		"Sets the timeout for the requests issued to the SQLX services.",
		OIO_SQLX_OUTGOING_TIMEOUT_REQ, 0.01, 60.0);
}
