/*
Copyright (C) 2017-2019 OpenIO SAS, as part of OpenIO SDS

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library.
*/

#include "lb_variables.h" /* AUTO-GENERATED by confgen.py */

gboolean oio_lb_allow_distance_bypass = OIO_CORE_LB_ALLOW_DISTANCE_BYPASS;
guint oio_lb_weighted_random_attempts = OIO_CORE_LB_WEIGHTED_RANDOM_ATTEMPTS;
gint64 oio_lb_writer_lock_alert_delay = OIO_CORE_LB_WRITER_LOCK_ALERT_DELAY;

static void __attribute__ ((constructor))
_declare_gboolean_OIO__OIO_SDS_CORE_LB_VARIABLES_H_ (void) {

	oio_var_register_gboolean(
		&oio_lb_allow_distance_bypass, "core.lb.allow_distance_bypass",
		"Compare the number of items to select to the number of items available at the current location level, and decide if it is desirable to bypass or slacken the time-consuming distance checks. Disable this if you detect too many situations where distance between selected items could have been bigger.",
		OIO_CORE_LB_ALLOW_DISTANCE_BYPASS);

	oio_var_register_guint(
		&oio_lb_weighted_random_attempts, OIO_VARKIND_size, "core.lb.weighted_random_attempts",
		"How many times shall we try to select a service using a weighted random algorithm, before switching to the shuffled selection. Increase this if you observe too many choices of low-score services while high-score services are available.",
		OIO_CORE_LB_WEIGHTED_RANDOM_ATTEMPTS, 1, 64000);

	oio_var_register_gint64(
		&oio_lb_writer_lock_alert_delay, OIO_VARKIND_time, "core.lb.writer_lock_alert_delay",
		"Dump the time spent while holding the global writer lock, when the lock is held for longer than this threshold (in microseconds).",
		OIO_CORE_LB_WRITER_LOCK_ALERT_DELAY, 1, 60 * G_TIME_SPAN_SECOND);
}
