/*
Copyright (C) 2017-2019 OpenIO SAS, as part of OpenIO SDS

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library.
*/

#ifndef OIO__OIO_SDS_CORE_LB_VARIABLES_H_
#define OIO__OIO_SDS_CORE_LB_VARIABLES_H_

#include "core/oiovar.h"

/* AUTO-GENERATED by confgen.py */

#ifndef OIO_CORE_LB_ALLOW_DISTANCE_BYPASS
# define OIO_CORE_LB_ALLOW_DISTANCE_BYPASS (TRUE)
#endif

extern gboolean oio_lb_allow_distance_bypass;

#ifndef OIO_CORE_LB_WEIGHTED_RANDOM_ATTEMPTS
# define OIO_CORE_LB_WEIGHTED_RANDOM_ATTEMPTS (1)
#endif

extern guint oio_lb_weighted_random_attempts;

#ifndef OIO_CORE_LB_WRITER_LOCK_ALERT_DELAY
# define OIO_CORE_LB_WRITER_LOCK_ALERT_DELAY (5000)
#endif

extern gint64 oio_lb_writer_lock_alert_delay;


#endif /* OIO__OIO_SDS_CORE_LB_VARIABLES_H_ */
