/*
Copyright (C) 2017-2019 OpenIO SAS, as part of OpenIO SDS

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library.
*/

#include "sqliterepo_remote_variables.h" /* AUTO-GENERATED by confgen.py */

gdouble oio_election_getvers_timeout_cnx = OIO_SQLITEREPO_OUTGOING_TIMEOUT_CNX_GETVERS;
gdouble oio_election_replicate_timeout_cnx = OIO_SQLITEREPO_OUTGOING_TIMEOUT_CNX_REPLICATE;
gdouble oio_election_resync_timeout_cnx = OIO_SQLITEREPO_OUTGOING_TIMEOUT_CNX_RESYNC;
gdouble oio_election_use_timeout_cnx = OIO_SQLITEREPO_OUTGOING_TIMEOUT_CNX_USE;
gdouble oio_election_getvers_timeout_req = OIO_SQLITEREPO_OUTGOING_TIMEOUT_REQ_GETVERS;
gdouble oio_election_replicate_timeout_req = OIO_SQLITEREPO_OUTGOING_TIMEOUT_REQ_REPLICATE;
gdouble oio_election_resync_timeout_req = OIO_SQLITEREPO_OUTGOING_TIMEOUT_REQ_RESYNC;
gdouble oio_election_use_timeout_req = OIO_SQLITEREPO_OUTGOING_TIMEOUT_REQ_USE;

static void __attribute__ ((constructor))
_declare_gboolean_OIO__OIO_SDS_SQLITEREPO_SQLITEREPO_REMOTE_VARIABLES_H_ (void) {

	oio_var_register_gdouble(
		&oio_election_getvers_timeout_cnx, OIO_VARKIND_time, "sqliterepo.outgoing.timeout.cnx.getvers",
		"Sets the connection timeout when exchanging versions between databases replicas.",
		OIO_SQLITEREPO_OUTGOING_TIMEOUT_CNX_GETVERS, 0.01, 30.0);

	oio_var_register_gdouble(
		&oio_election_replicate_timeout_cnx, OIO_VARKIND_time, "sqliterepo.outgoing.timeout.cnx.replicate",
		"Sets the connection timeout sending a replication request.",
		OIO_SQLITEREPO_OUTGOING_TIMEOUT_CNX_REPLICATE, 0.01, 30.0);

	oio_var_register_gdouble(
		&oio_election_resync_timeout_cnx, OIO_VARKIND_time, "sqliterepo.outgoing.timeout.cnx.resync",
		"Set the connection timeout during RPC to ask for a SLAVE database to be resync on its MASTER",
		OIO_SQLITEREPO_OUTGOING_TIMEOUT_CNX_RESYNC, 0.01, 30.0);

	oio_var_register_gdouble(
		&oio_election_use_timeout_cnx, OIO_VARKIND_time, "sqliterepo.outgoing.timeout.cnx.use",
		"Sets the connection timeout when ping'ing a peer database. Keep it small. Only used when UDP is disabled.",
		OIO_SQLITEREPO_OUTGOING_TIMEOUT_CNX_USE, 0.01, 30.0);

	oio_var_register_gdouble(
		&oio_election_getvers_timeout_req, OIO_VARKIND_time, "sqliterepo.outgoing.timeout.req.getvers",
		"Sets the global timeout when performing a version exchange RPC. Keep it rather small, to let election quickly fail on network troubles. Only used when UDP is disabled.",
		OIO_SQLITEREPO_OUTGOING_TIMEOUT_REQ_GETVERS, 0.01, 30.0);

	oio_var_register_gdouble(
		&oio_election_replicate_timeout_req, OIO_VARKIND_time, "sqliterepo.outgoing.timeout.req.replicate",
		"Sets the global timeout when sending a replication RPC, from the current MASTER to a SLAVE",
		OIO_SQLITEREPO_OUTGOING_TIMEOUT_REQ_REPLICATE, 0.01, 30.0);

	oio_var_register_gdouble(
		&oio_election_resync_timeout_req, OIO_VARKIND_time, "sqliterepo.outgoing.timeout.req.resync",
		"Sets the global timeout of a RESYNC request sent to a 'meta' service. Sent to a SLAVE DB, the RESYNC operation involves a RPC from the SLAVE to the MASTER, then a DB dump on the MASTER and restoration on the SLAVE. Thus that operation might be rather long, due to the possibility of network/disk latency/bandwidth, etc. Should be set accordingly with sqliterepo.dumps.timeout",
		OIO_SQLITEREPO_OUTGOING_TIMEOUT_REQ_RESYNC, 0.01, 300.0);

	oio_var_register_gdouble(
		&oio_election_use_timeout_req, OIO_VARKIND_time, "sqliterepo.outgoing.timeout.req.use",
		"Sets the global timeout when ping'ing a peer database. Keep it small.",
		OIO_SQLITEREPO_OUTGOING_TIMEOUT_REQ_USE, 0.01, 30.0);
}
