/*
Copyright (C) 2017-2019 OpenIO SAS, as part of OpenIO SDS

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3.0 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library.
*/

#ifndef OIO__OIO_SDS_SQLITEREPO_SQLITEREPO_REMOTE_VARIABLES_H_
#define OIO__OIO_SDS_SQLITEREPO_SQLITEREPO_REMOTE_VARIABLES_H_

#include "core/oiovar.h"

/* AUTO-GENERATED by confgen.py */

#ifndef OIO_SQLITEREPO_OUTGOING_TIMEOUT_CNX_GETVERS
# define OIO_SQLITEREPO_OUTGOING_TIMEOUT_CNX_GETVERS (5.0)
#endif

extern gdouble oio_election_getvers_timeout_cnx;

#ifndef OIO_SQLITEREPO_OUTGOING_TIMEOUT_CNX_REPLICATE
# define OIO_SQLITEREPO_OUTGOING_TIMEOUT_CNX_REPLICATE (5.0)
#endif

extern gdouble oio_election_replicate_timeout_cnx;

#ifndef OIO_SQLITEREPO_OUTGOING_TIMEOUT_CNX_RESYNC
# define OIO_SQLITEREPO_OUTGOING_TIMEOUT_CNX_RESYNC (5.0)
#endif

extern gdouble oio_election_resync_timeout_cnx;

#ifndef OIO_SQLITEREPO_OUTGOING_TIMEOUT_CNX_USE
# define OIO_SQLITEREPO_OUTGOING_TIMEOUT_CNX_USE (1.0)
#endif

extern gdouble oio_election_use_timeout_cnx;

#ifndef OIO_SQLITEREPO_OUTGOING_TIMEOUT_REQ_GETVERS
# define OIO_SQLITEREPO_OUTGOING_TIMEOUT_REQ_GETVERS (10.0)
#endif

extern gdouble oio_election_getvers_timeout_req;

#ifndef OIO_SQLITEREPO_OUTGOING_TIMEOUT_REQ_REPLICATE
# define OIO_SQLITEREPO_OUTGOING_TIMEOUT_REQ_REPLICATE (10.0)
#endif

extern gdouble oio_election_replicate_timeout_req;

#ifndef OIO_SQLITEREPO_OUTGOING_TIMEOUT_REQ_RESYNC
# define OIO_SQLITEREPO_OUTGOING_TIMEOUT_REQ_RESYNC (241.0)
#endif

extern gdouble oio_election_resync_timeout_req;

#ifndef OIO_SQLITEREPO_OUTGOING_TIMEOUT_REQ_USE
# define OIO_SQLITEREPO_OUTGOING_TIMEOUT_REQ_USE (10.0)
#endif

extern gdouble oio_election_use_timeout_req;


#endif /* OIO__OIO_SDS_SQLITEREPO_SQLITEREPO_REMOTE_VARIABLES_H_ */
