/*
Copyright (C) 2017-2017 OpenIO SAS, as part of OpenIO SDS

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/* !!!AUTOGENERATED!!! */
#include <metautils/lib/metautils.h>
#include <meta2v2/generic.h>
#include <meta2v2/autogen.h>
#include <glib.h>
#include <sqlite3.h>

GError*
CONTENTS_HEADERS_load(sqlite3 *db, const gchar *clause, GVariant **params, void (*cb)(gpointer u, gpointer bean), gpointer u)
{
	EXTRA_ASSERT(db != NULL);
	EXTRA_ASSERT(clause != NULL);
	EXTRA_ASSERT(params != NULL);
	return _db_get_bean(&descr_struct_CONTENTS_HEADERS, db, clause, params, cb, u);
}

GError*
CHUNKS_load(sqlite3 *db, const gchar *clause, GVariant **params, void (*cb)(gpointer u, gpointer bean), gpointer u)
{
	EXTRA_ASSERT(db != NULL);
	EXTRA_ASSERT(clause != NULL);
	EXTRA_ASSERT(params != NULL);
	return _db_get_bean(&descr_struct_CHUNKS, db, clause, params, cb, u);
}

GError*
PROPERTIES_load(sqlite3 *db, const gchar *clause, GVariant **params, void (*cb)(gpointer u, gpointer bean), gpointer u)
{
	EXTRA_ASSERT(db != NULL);
	EXTRA_ASSERT(clause != NULL);
	EXTRA_ASSERT(params != NULL);
	return _db_get_bean(&descr_struct_PROPERTIES, db, clause, params, cb, u);
}

GError*
ALIASES_load(sqlite3 *db, const gchar *clause, GVariant **params, void (*cb)(gpointer u, gpointer bean), gpointer u)
{
	EXTRA_ASSERT(db != NULL);
	EXTRA_ASSERT(clause != NULL);
	EXTRA_ASSERT(params != NULL);
	return _db_get_bean(&descr_struct_ALIASES, db, clause, params, cb, u);
}

