/*
Copyright (C) 2017-2019 OpenIO SAS, as part of OpenIO SDS

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "meta2_variables.h" /* AUTO-GENERATED by confgen.py */

guint meta2_batch_maxlen = OIO_META2_BATCH_MAXLEN;
gint64 meta2_container_max_size = OIO_META2_CONTAINER_MAX_SIZE;
gboolean meta2_flag_delete_exceeding_versions = OIO_META2_DELETE_EXCEEDING_VERSIONS;
gint64 meta2_flush_limit = OIO_META2_FLUSH_LIMIT;
gboolean meta2_flag_precheck_on_generate = OIO_META2_GENERATE_PRECHECK;
gint64 meta2_reload_lb_period = OIO_META2_RELOAD_LB_PERIOD;
gint64 meta2_reload_nsinfo_period = OIO_META2_RELOAD_NSINFO_PERIOD;
gint64 meta2_retention_period = OIO_META2_RETENTION_PERIOD;

static void __attribute__ ((constructor))
_declare_gboolean_OIO__OIO_SDS_META2V2_META2_VARIABLES_H_ (void) {

	oio_var_register_guint(
		&meta2_batch_maxlen, OIO_VARKIND_size, "meta2.batch.maxlen",
		"When listing a container, limits the number of items to that value.",
		OIO_META2_BATCH_MAXLEN, 1, 100000);

	oio_var_register_gint64(
		&meta2_container_max_size, OIO_VARKIND_size, "meta2.container.max_size",
		"How many bytes may be stored in each container.",
		OIO_META2_CONTAINER_MAX_SIZE, 0, G_MAXINT64);

	oio_var_register_gboolean(
		&meta2_flag_delete_exceeding_versions, "meta2.delete_exceeding_versions",
		"When adding alias with versioning, deletes exceeding versions.",
		OIO_META2_DELETE_EXCEEDING_VERSIONS);

	oio_var_register_gint64(
		&meta2_flush_limit, OIO_VARKIND_size, "meta2.flush_limit",
		"When flushing a container, limits the number of deleted objects.",
		OIO_META2_FLUSH_LIMIT, 0, G_MAXINT64);

	oio_var_register_gboolean(
		&meta2_flag_precheck_on_generate, "meta2.generate.precheck",
		"Should the meta2 check the container state (quota, etc) before generating chunks.",
		OIO_META2_GENERATE_PRECHECK);

	oio_var_register_gint64(
		&meta2_reload_lb_period, OIO_VARKIND_epoch, "meta2.reload.lb.period",
		"Sets the period of the periodical reloading of the Load-balancing state, in the current meta2 service.",
		OIO_META2_RELOAD_LB_PERIOD, 1, 3600);

	oio_var_register_gint64(
		&meta2_reload_nsinfo_period, OIO_VARKIND_epoch, "meta2.reload.nsinfo.period",
		"Sets the period of the periodical reloading of the namespace configuration, in the current meta2 service.",
		OIO_META2_RELOAD_NSINFO_PERIOD, 1, 3600);

	oio_var_register_gint64(
		&meta2_retention_period, OIO_VARKIND_epoch, "meta2.retention_period",
		"How long should deleted content be kept.",
		OIO_META2_RETENTION_PERIOD, 1, 2592000);
}
