/*
Copyright (C) 2017-2019 OpenIO SAS, as part of OpenIO SDS

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef OIO__OIO_SDS_META2V2_META2_VARIABLES_H_
#define OIO__OIO_SDS_META2V2_META2_VARIABLES_H_

#include "core/oiovar.h"

/* AUTO-GENERATED by confgen.py */

#ifndef OIO_META2_BATCH_MAXLEN
# define OIO_META2_BATCH_MAXLEN (1000)
#endif

extern guint meta2_batch_maxlen;

#ifndef OIO_META2_CONTAINER_MAX_SIZE
# define OIO_META2_CONTAINER_MAX_SIZE (0)
#endif

extern gint64 meta2_container_max_size;

#ifndef OIO_META2_DELETE_EXCEEDING_VERSIONS
# define OIO_META2_DELETE_EXCEEDING_VERSIONS (FALSE)
#endif

extern gboolean meta2_flag_delete_exceeding_versions;

#ifndef OIO_META2_FLUSH_LIMIT
# define OIO_META2_FLUSH_LIMIT (1000)
#endif

extern gint64 meta2_flush_limit;

#ifndef OIO_META2_GENERATE_PRECHECK
# define OIO_META2_GENERATE_PRECHECK (FALSE)
#endif

extern gboolean meta2_flag_precheck_on_generate;

#ifndef OIO_META2_RELOAD_LB_PERIOD
# define OIO_META2_RELOAD_LB_PERIOD (10)
#endif

extern gint64 meta2_reload_lb_period;

#ifndef OIO_META2_RELOAD_NSINFO_PERIOD
# define OIO_META2_RELOAD_NSINFO_PERIOD (5)
#endif

extern gint64 meta2_reload_nsinfo_period;

#ifndef OIO_META2_RETENTION_PERIOD
# define OIO_META2_RETENTION_PERIOD (604800)
#endif

extern gint64 meta2_retention_period;


#endif /* OIO__OIO_SDS_META2V2_META2_VARIABLES_H_ */
