/*
Copyright (C) 2017-2019 OpenIO SAS, as part of OpenIO SDS

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "resolver_variables.h" /* AUTO-GENERATED by confgen.py */

gboolean oio_resolver_dir_shuffle = OIO_CORE_RESOLVER_DIR_SHUFFLE;
gboolean oio_resolver_srv_shuffle = OIO_CORE_RESOLVER_SRV_SHUFFLE;
guint oio_resolver_m0cs_default_max = OIO_RESOLVER_CACHE_CSM0_MAX_DEFAULT;
gint64 oio_resolver_m0cs_default_ttl = OIO_RESOLVER_CACHE_CSM0_TTL_DEFAULT;
gboolean oio_resolver_cache_enabled = OIO_RESOLVER_CACHE_ENABLED;
guint oio_resolver_srv_default_max = OIO_RESOLVER_CACHE_SRV_MAX_DEFAULT;
gint64 oio_resolver_srv_default_ttl = OIO_RESOLVER_CACHE_SRV_TTL_DEFAULT;

static void __attribute__ ((constructor))
_declare_gboolean_OIO__OIO_SDS_RESOLVER_RESOLVER_VARIABLES_H_ (void) {

	oio_var_register_gboolean(
		&oio_resolver_dir_shuffle, "core.resolver.dir_shuffle",
		"TODO: to be documented",
		OIO_CORE_RESOLVER_DIR_SHUFFLE);

	oio_var_register_gboolean(
		&oio_resolver_srv_shuffle, "core.resolver.srv_shuffle",
		"TODO: to be documented",
		OIO_CORE_RESOLVER_SRV_SHUFFLE);

	oio_var_register_guint(
		&oio_resolver_m0cs_default_max, OIO_VARKIND_size, "resolver.cache.csm0.max.default",
		"In any service resolver instanciated, sets the maximum number of entries related to meta0 (meta1 addresses) and conscience (meta0 address)",
		OIO_RESOLVER_CACHE_CSM0_MAX_DEFAULT, 0, G_MAXUINT);

	oio_var_register_gint64(
		&oio_resolver_m0cs_default_ttl, OIO_VARKIND_time, "resolver.cache.csm0.ttl.default",
		"In any service resolver instanciated, sets the default TTL on the entries related meta0 (meta1 addresses) and conscience (meta0 address)",
		OIO_RESOLVER_CACHE_CSM0_TTL_DEFAULT, 0, G_MAXINT64);

	oio_var_register_gboolean(
		&oio_resolver_cache_enabled, "resolver.cache.enabled",
		"Allows the resolver instances to cache entries",
		OIO_RESOLVER_CACHE_ENABLED);

	oio_var_register_guint(
		&oio_resolver_srv_default_max, OIO_VARKIND_size, "resolver.cache.srv.max.default",
		"In any service resolver instanciated, sets the maximum number of meta1 entries (data-bound services)",
		OIO_RESOLVER_CACHE_SRV_MAX_DEFAULT, 0, G_MAXUINT);

	oio_var_register_gint64(
		&oio_resolver_srv_default_ttl, OIO_VARKIND_time, "resolver.cache.srv.ttl.default",
		"In any service resolver instanciated, sets the default TTL on the meta1 entries (data-bound services)",
		OIO_RESOLVER_CACHE_SRV_TTL_DEFAULT, 0, G_MAXINT64);
}
